force-app/main/default/objects/Case/fields/TestClosedDate__c.field-meta.xml
<CustomField>
    <fullName>TestClosedDate__c</fullName>
    <description>Used for testing purposes. Can be used to copy the value in Case.ClosedDate and be make non-editable</description>
    <label>TestClosedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <description>Used for storing erros that are thrown in code.</description>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DL{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the class the error was created from</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchGDPRCleaner.cls
/**
 * @class: BatchGDPRCleaner
 * @test: BatchGDPRCleanerTest
 * @desc: Batch job for cleaning data from records linked to and including a base Case record.
 *        Related SObjects include: Account and Contact
 */
global class BatchGDPRCleaner implements Database.Batchable<sObject>, Database.Stateful {

    Date filterClosedDate = Date.today().addYears(-1);

    /**
     * Query to get the records to work with
     */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String databaseQuery = '';
        databaseQuery += 'SELECT Id, AccountId, ContactId\n';
        databaseQuery += 'FROM Case\n';
        databaseQuery += 'WHERE TestClosedDate__c < :filterClosedDate\n';
        databaseQuery += '  AND (AccountId != null OR ContactId != null)\n';

        return Database.getQueryLocator( databaseQuery );
    }

    /**
     * Logic goes here
     */
    global void execute(Database.BatchableContext bc, List<Case> queriedCases) {
        Set<Id> caseIds = (new Map<Id, Case>(queriedCases)).keySet();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();

        //  Get related Account and Contact record Ids
        for (Case caseToClean : queriedCases) {
            accountIds.add(caseToClean.AccountId);
            contactIds.add(caseToClean.ContactId);
        }

        //  Clean data
        List<Case> updatedCases = UtilityGDPRCleaner.cleanDataCases(queriedCases);
        List<Account> updatedAccounts = UtilityGDPRCleaner.cleanDataAccounts([
            SELECT Id FROM Account WHERE Id IN :accountIds
        ]);
        List<Contact> updatedContacts = UtilityGDPRCleaner.cleanDataContacts([
            SELECT Id FROM Contact WHERE Id IN :contactIds
        ]);

        //  Updating records
        List<Database.SaveResult> saveResults = Database.update(updatedCases, false);
        saveResults.addAll( Database.update(updatedAccounts, false) );
        saveResults.addAll( Database.update(updatedContacts, false) );
        System.debug(saveResults);

        //  Create additional Debug Logs
        List<Debug_Log__c> newDebugLogs = UtilityGDPRCleaner.retrieveGeneratedDebugRecords();
        for (Database.SaveResult sr : saveResults) {
            if (!sr.isSuccess()) {
                for (Database.Error dbErr : sr.getErrors()) {
                    String customErrorMessage = '';
                    customErrorMessage += 'Status Code: ' + String.valueOf(dbErr.getStatusCode()) + '\n';
                    customErrorMessage += 'Affeccted fields: ' + dbErr.getFields() + '\n';
                    customErrorMessage += 'Error Message: ' + dbErr.getMessage() + '\n';

                    newDebugLogs.add(new Debug_Log__c(
                        Class_Name__c = 'BatchGDPRCleaner',
                        Error_Message__c = customErrorMessage
                    ));
                }
            }
        }
        if (!newDebugLogs.isEmpty()) {
            insert newDebugLogs;
        }
    }

    /**
     * Reporting goes here. E.g. Sending emails, create new records to report on batch
     */
    global void finish(Database.BatchableContext bc) {
        //  Could add email notification here
    }
}